### ISSUE TITLE
Issue: No account for user with no profile source.

### ISSUE THREAD

**Issue by skully-coder** [GDSCASIET/30daysofgooglecloud-asiet#11]
Hey there, I am a facilitator for 30 Days of Google Cloud too. I found a small issue in your code that does not account for the people whose qwiklabs profiles do not have a profile picture or they have an anonymous profile picture, i.e, the `src` of the image is 
`https://www.gstatic.com/images/branding/product/2x/avatar_anonymous_512dp.png`. I have found a fix and will be creating a pull request too. I see that you have labelled your repo with a `hacktoberfest` tag as well, so it would mean a lot to me if you accept the PR.

**Comment by GDSCASIET** [comment]
Hi, I am not sure why you made the issue as "Number of people found in my.json is wrong". Anyway, we did take that into account for people with no name or no profile pic. But all of them had, and qwiklabs do use name letter profile pic if someone didn't upload it. So we didn't bother to include it.
